package GUI;

import BUS.BangCapBUS;
import BUS.NhanVienBUS;
import BUS.ThamgiaDuanBUS;
import BUS.ViPham_BUS;
import DTO.BangCapDTO;
import DTO.NhanVienDTO;
import DTO.ThamgiaDuanDTO;
import DTO.ViPham_DTO;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class LuongGUI extends javax.swing.JPanel {

    private static final double HSL = 1.86;
    
    public LuongGUI() {
        initComponents();
        rebuildFrame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnLuongNV = new javax.swing.JPanel();
        pnTimKiemLuongNV = new javax.swing.JPanel();
        lbTimKiemLuong = new javax.swing.JLabel();
        tfLuongNV = new javax.swing.JTextField();
        spTimKiemLuongNV = new javax.swing.JScrollPane();
        tbNV = new javax.swing.JTable();
        jComboBox5 = new javax.swing.JComboBox<>();
        lbLuong = new javax.swing.JLabel();
        lbIDNVLuong = new javax.swing.JLabel();
        lbTenNVLuong = new javax.swing.JLabel();
        tfTenNVLuong = new javax.swing.JTextField();
        tfIDNVLuong = new javax.swing.JTextField();
        lbImageLuong = new javax.swing.JLabel();
        pnBangTinhLuong = new javax.swing.JPanel();
        lbBangTinhLuong = new javax.swing.JLabel();
        lbLuongCoBan = new javax.swing.JLabel();
        tfLuongCoBan = new javax.swing.JTextField();
        lbPCCV = new javax.swing.JLabel();
        tfThuongBangCap = new javax.swing.JTextField();
        lbSoNgayLamViec = new javax.swing.JLabel();
        tfSoNgayLamViec = new javax.swing.JTextField();
        lbKTVP = new javax.swing.JLabel();
        tfKTVP = new javax.swing.JTextField();
        lbTongLuong = new javax.swing.JLabel();
        tfTongLuong = new javax.swing.JTextField();
        btnTinhLuong = new javax.swing.JButton();
        lbThuongDuan = new javax.swing.JLabel();
        tfThuongDuan = new javax.swing.JTextField();

        pnTimKiemLuongNV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbTimKiemLuong.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lbTimKiemLuong.setText("Tìm kiếm");

        tfLuongNV.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        tfLuongNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLuongNVActionPerformed(evt);
            }
        });

        tbNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên nhân viên", "Giới tính ", "Ngày sinh", "Số điện thoại", "Email", "Tình trạng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbNV.setRowHeight(25);
        spTimKiemLuongNV.setViewportView(tbNV);
        if (tbNV.getColumnModel().getColumnCount() > 0) {
            tbNV.getColumnModel().getColumn(0).setMinWidth(80);
            tbNV.getColumnModel().getColumn(0).setMaxWidth(80);
            tbNV.getColumnModel().getColumn(1).setMinWidth(220);
            tbNV.getColumnModel().getColumn(1).setMaxWidth(220);
            tbNV.getColumnModel().getColumn(2).setMinWidth(80);
            tbNV.getColumnModel().getColumn(2).setMaxWidth(80);
        }

        jComboBox5.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "ID", "Tên nhân viên", "Giới tính", "Ngày sinh", "Số điện thoại", "Email", "Tình trạng" }));

        javax.swing.GroupLayout pnTimKiemLuongNVLayout = new javax.swing.GroupLayout(pnTimKiemLuongNV);
        pnTimKiemLuongNV.setLayout(pnTimKiemLuongNVLayout);
        pnTimKiemLuongNVLayout.setHorizontalGroup(
            pnTimKiemLuongNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiemLuongNVLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbTimKiemLuong)
                .addGap(18, 18, 18)
                .addComponent(tfLuongNV, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(512, Short.MAX_VALUE))
            .addGroup(pnTimKiemLuongNVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spTimKiemLuongNV)
                .addContainerGap())
        );
        pnTimKiemLuongNVLayout.setVerticalGroup(
            pnTimKiemLuongNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiemLuongNVLayout.createSequentialGroup()
                .addGroup(pnTimKiemLuongNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTimKiemLuongNVLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnTimKiemLuongNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTimKiemLuong)
                            .addComponent(tfLuongNV, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(pnTimKiemLuongNVLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(spTimKiemLuongNV, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        lbLuong.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        lbLuong.setText("Lương nhân viên");

        lbIDNVLuong.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lbIDNVLuong.setText("Mã nhân viên");

        lbTenNVLuong.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lbTenNVLuong.setText("Tên nhân viên");

        tfTenNVLuong.setFont(new java.awt.Font("Segoe UI Light", 1, 13)); // NOI18N
        tfTenNVLuong.setEnabled(false);

        tfIDNVLuong.setFont(new java.awt.Font("Segoe UI Light", 1, 13)); // NOI18N
        tfIDNVLuong.setEnabled(false);

        lbImageLuong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnBangTinhLuong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lbBangTinhLuong.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lbBangTinhLuong.setText("Bảng tính lương");

        lbLuongCoBan.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lbLuongCoBan.setText("Lương cơ bản");

        tfLuongCoBan.setEditable(false);
        tfLuongCoBan.setFont(new java.awt.Font("Segoe UI Light", 1, 13)); // NOI18N

        lbPCCV.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lbPCCV.setText("Thưởng bằng cấp");

        tfThuongBangCap.setEditable(false);
        tfThuongBangCap.setFont(new java.awt.Font("Segoe UI Light", 1, 13)); // NOI18N
        tfThuongBangCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfThuongBangCapActionPerformed(evt);
            }
        });

        lbSoNgayLamViec.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lbSoNgayLamViec.setText("Số ngày làm việc");

        tfSoNgayLamViec.setFont(new java.awt.Font("Segoe UI Light", 1, 13)); // NOI18N

        lbKTVP.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lbKTVP.setText("Khấu trừ vi phạm");

        tfKTVP.setEditable(false);
        tfKTVP.setFont(new java.awt.Font("Segoe UI Light", 1, 13)); // NOI18N

        lbTongLuong.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lbTongLuong.setText("Tổng lương");

        tfTongLuong.setEditable(false);
        tfTongLuong.setFont(new java.awt.Font("Segoe UI Light", 1, 13)); // NOI18N

        btnTinhLuong.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnTinhLuong.setText("Tính lương");
        btnTinhLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhLuongActionPerformed(evt);
            }
        });

        lbThuongDuan.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lbThuongDuan.setText("Thưởng dự án");

        tfThuongDuan.setEditable(false);
        tfThuongDuan.setFont(new java.awt.Font("Segoe UI Light", 1, 13)); // NOI18N

        javax.swing.GroupLayout pnBangTinhLuongLayout = new javax.swing.GroupLayout(pnBangTinhLuong);
        pnBangTinhLuong.setLayout(pnBangTinhLuongLayout);
        pnBangTinhLuongLayout.setHorizontalGroup(
            pnBangTinhLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBangTinhLuongLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnBangTinhLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBangTinhLuongLayout.createSequentialGroup()
                        .addComponent(lbBangTinhLuong)
                        .addGap(146, 146, 146))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBangTinhLuongLayout.createSequentialGroup()
                        .addComponent(btnTinhLuong)
                        .addGap(152, 152, 152))))
            .addGroup(pnBangTinhLuongLayout.createSequentialGroup()
                .addGroup(pnBangTinhLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBangTinhLuongLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(pnBangTinhLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnBangTinhLuongLayout.createSequentialGroup()
                                .addGroup(pnBangTinhLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbSoNgayLamViec)
                                    .addComponent(lbThuongDuan)
                                    .addComponent(lbKTVP, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(pnBangTinhLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfKTVP, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfSoNgayLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfThuongDuan, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnBangTinhLuongLayout.createSequentialGroup()
                                .addGroup(pnBangTinhLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbLuongCoBan)
                                    .addComponent(lbPCCV))
                                .addGap(26, 26, 26)
                                .addGroup(pnBangTinhLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfThuongBangCap, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfLuongCoBan, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pnBangTinhLuongLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lbTongLuong)
                        .addGap(18, 18, 18)
                        .addComponent(tfTongLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        pnBangTinhLuongLayout.setVerticalGroup(
            pnBangTinhLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBangTinhLuongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbBangTinhLuong)
                .addGap(9, 9, 9)
                .addGroup(pnBangTinhLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLuongCoBan)
                    .addComponent(tfLuongCoBan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnBangTinhLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfThuongBangCap, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPCCV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnBangTinhLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfThuongDuan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbThuongDuan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnBangTinhLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSoNgayLamViec)
                    .addComponent(tfSoNgayLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnBangTinhLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbKTVP)
                    .addComponent(tfKTVP, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnBangTinhLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTongLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTongLuong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnTinhLuong)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout pnLuongNVLayout = new javax.swing.GroupLayout(pnLuongNV);
        pnLuongNV.setLayout(pnLuongNVLayout);
        pnLuongNVLayout.setHorizontalGroup(
            pnLuongNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLuongNVLayout.createSequentialGroup()
                .addGroup(pnLuongNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnLuongNVLayout.createSequentialGroup()
                        .addGroup(pnLuongNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnLuongNVLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(pnLuongNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnLuongNVLayout.createSequentialGroup()
                                        .addComponent(lbTenNVLuong)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tfTenNVLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnLuongNVLayout.createSequentialGroup()
                                        .addComponent(lbIDNVLuong)
                                        .addGap(41, 41, 41)
                                        .addComponent(tfIDNVLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnLuongNVLayout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(lbImageLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(102, 102, 102)
                        .addComponent(pnBangTinhLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnLuongNVLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnLuongNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbLuong)
                            .addComponent(pnTimKiemLuongNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnLuongNVLayout.setVerticalGroup(
            pnLuongNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLuongNVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbLuong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnLuongNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnLuongNVLayout.createSequentialGroup()
                        .addComponent(lbImageLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnLuongNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbIDNVLuong)
                            .addComponent(tfIDNVLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnLuongNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTenNVLuong)
                            .addComponent(tfTenNVLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnBangTinhLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnTimKiemLuongNV, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnLuongNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnLuongNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void rebuildFrame() {
        loadListNV();
        addMouseEvent();
    }
    
    
    // <editor-fold defaultstate="collapsed" desc="Event Handling">  
    private void loadListNV() {
        try {
            if (NhanVienBUS.dsnv == null || NhanVienBUS.dsnv.isEmpty()) new NhanVienBUS().docDSNV();
            if (BangCapBUS.dsbc == null || BangCapBUS.dsbc.isEmpty()) new BangCapBUS().docDSBC();
            if (ThamgiaDuanBUS.dstongquat == null || ThamgiaDuanBUS.dstongquat.isEmpty()) new ThamgiaDuanBUS().docDSTGDA();
            //Khởi tạo table NV
            DefaultTableModel model = (DefaultTableModel) tbNV.getModel();
            for (NhanVienDTO nv:NhanVienBUS.dsnv) 
                if (nv.visible == 1) {
                    Vector row = new Vector();
                    row.add(nv.id); 
                    row.add(nv.name); 
                    if (nv.gioitinh == 1)
                    row.add("Nam"); else row.add("Nữ");
                    row.add(nv.ngaysinh); 
                    row.add(nv.sdt); 
                    row.add(nv.email); 
                    if (nv.tinhtrang == 1)
                    row.add("Còn làm việc"); else row.add("Đã nghỉ làm");
                    model.addRow(row);
                }
            tbNV.setModel(model);
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }
    
    private void addMouseEvent() {
        //thêm event cho frame và table
        pnLuongNV.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                resetForm();
            }
        });
        pnTimKiemLuongNV.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                resetForm();
            }
        });
        tbNV.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                DefaultTableModel model = (DefaultTableModel) tbNV.getModel();
                int rowPos = tbNV.getSelectedRow();
                String idnv = model.getValueAt(rowPos, 0).toString().trim();
                String tennv = model.getValueAt(rowPos, 1).toString().trim();
                ArrayList<ViPham_DTO> listvp = new ViPham_BUS().getAllViPham();
                boolean check = false;
                tfIDNVLuong.setText(idnv);
                tfTenNVLuong.setText(tennv);
                for (NhanVienDTO nv:NhanVienBUS.dsnv)
                    if (nv.id.equals(idnv)) {
                        ImageIcon myimage = new ImageIcon(nv.hinhanh);
                        Image img = myimage.getImage();
                        Image resizeimg = img.getScaledInstance(lbImageLuong.getWidth(), lbImageLuong.getHeight(),Image.SCALE_SMOOTH);
                        lbImageLuong.setIcon(new ImageIcon(resizeimg));
                        tfLuongCoBan.setText(String.valueOf(nv.getLuong() + nv.getPhucap()));
                        for (BangCapDTO bc:BangCapBUS.dsbc)
                            if (nv.id_bangcap == bc.id) {
                                tfThuongBangCap.setText(String.valueOf(bc.thuongbangcap));
                                break;
                            }
                        break;
                    }
                for (ThamgiaDuanDTO tgda:ThamgiaDuanBUS.dstongquat)
                    if (idnv.equals(tgda.idnv)) {
                        int tongtien = 0;
                        tongtien += tgda.thuongduan;
                        tfThuongDuan.setText(String.valueOf(tongtien));
                        check = true;
                    }
                if (check == false) tfThuongDuan.setText("0");
                check = false;
                for (ViPham_DTO vp:listvp)
                    if (idnv.equals(vp.getID_nhanvien()) && vp.getVisible() == 1) {
                        int tongtien = 0;
                        tongtien += vp.getTienphat();
                        tfKTVP.setText(String.valueOf(tongtien));
                        check = true;
                    } 
                if (check == false) tfKTVP.setText("0");
            }
        });
    }
    
    private void resetForm() {
        tbNV.getSelectionModel().clearSelection();
        tfIDNVLuong.setText("");
        tfTenNVLuong.setText("");
    }
    
    private void tfLuongNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLuongNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLuongNVActionPerformed

    private void tfThuongBangCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfThuongBangCapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfThuongBangCapActionPerformed

    private void btnTinhLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhLuongActionPerformed
        if (checkField()) {
            double tongluong = 0;
            int lcb = Integer.parseInt(tfLuongCoBan.getText());
            int thuongbc = Integer.parseInt(tfThuongBangCap.getText());
            int thuongda = Integer.parseInt(tfThuongDuan.getText());
            int tienphat = Integer.parseInt(tfKTVP.getText());
            tongluong = (lcb + thuongbc + thuongda - tienphat) * HSL; 
            tfTongLuong.setText(String.valueOf((int) tongluong));
        }
    }//GEN-LAST:event_btnTinhLuongActionPerformed
    
    private boolean checkField() {
        if (tfSoNgayLamViec.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập số ngày làm việc!!", "Lỗi dữ liệu", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (!tfSoNgayLamViec.getText().equals("")) try {
            int num = Integer.parseInt(tfSoNgayLamViec.getText().trim());
            //nếu dưới 0 thì cố tình tạo lỗi
            if (num < 0) num = 1000/0;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Dữ liệu không hợp lệ!!", "Lỗi dữ liệu", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    //</editor-fold>

    
    // <editor-fold defaultstate="collapsed" desc="Variables Declaration">   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTinhLuong;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel lbBangTinhLuong;
    private javax.swing.JLabel lbIDNVLuong;
    private javax.swing.JLabel lbImageLuong;
    private javax.swing.JLabel lbKTVP;
    private javax.swing.JLabel lbLuong;
    private javax.swing.JLabel lbLuongCoBan;
    private javax.swing.JLabel lbPCCV;
    private javax.swing.JLabel lbSoNgayLamViec;
    private javax.swing.JLabel lbTenNVLuong;
    private javax.swing.JLabel lbThuongDuan;
    private javax.swing.JLabel lbTimKiemLuong;
    private javax.swing.JLabel lbTongLuong;
    private javax.swing.JPanel pnBangTinhLuong;
    private javax.swing.JPanel pnLuongNV;
    private javax.swing.JPanel pnTimKiemLuongNV;
    private javax.swing.JScrollPane spTimKiemLuongNV;
    private javax.swing.JTable tbNV;
    private javax.swing.JTextField tfIDNVLuong;
    private javax.swing.JTextField tfKTVP;
    private javax.swing.JTextField tfLuongCoBan;
    private javax.swing.JTextField tfLuongNV;
    private javax.swing.JTextField tfSoNgayLamViec;
    private javax.swing.JTextField tfTenNVLuong;
    private javax.swing.JTextField tfThuongBangCap;
    private javax.swing.JTextField tfThuongDuan;
    private javax.swing.JTextField tfTongLuong;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>
}
