package GUI;


import BUS.BangCapBUS;
import BUS.ChucVu_BUS;
import BUS.NhanVienBUS;
import BUS.PhongBanBUS;
import BUS.ThanNhan_BUS;
import DAO.NhanVienDAO;
import DTO.BangCapDTO;
import DTO.ChucVu_DTO;
import DTO.NhanVienDTO;
import DTO.PhongBanDTO;
import DTO.ThanNhan_DTO;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class NhanVienGUI extends javax.swing.JPanel {
    ThanNhan_BUS TNBUS=new ThanNhan_BUS();
    NhanVienDAO NVDAO;
    ArrayList<ThanNhan_DTO> arrTN=new ArrayList<ThanNhan_DTO>();
    DefaultTableModel modelTN;
    DefaultTableModel modelNVTN;
    public final Pattern VALID_EMAIL_ADDRESS_REGEX = Pattern.compile("^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$", Pattern.CASE_INSENSITIVE);
    //url ảnh hồ sơ
    String path = "";
    
    public NhanVienGUI() {
        initComponents();
        rebuildFrame();
        modelNVTN=(DefaultTableModel) tbNVTN.getModel();
        modelTN=(DefaultTableModel) tbNT.getModel();
        try {
            loadListNhanVienNhanThan();
        } catch (Exception ex) {
            System.out.println(ex);
        }
        loadListNhanThan();
        KhoiTaoBTN();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameNhanThan = new javax.swing.JFrame();
        lbTTNT = new javax.swing.JLabel();
        lbNVNT = new javax.swing.JLabel();
        lbMoiQuanHe = new javax.swing.JLabel();
        lbHTNT = new javax.swing.JLabel();
        lbSdtNT = new javax.swing.JLabel();
        lbNSNT = new javax.swing.JLabel();
        tfHTNT = new javax.swing.JTextField();
        tfNVNT = new javax.swing.JTextField();
        tfMoiQuanHe = new javax.swing.JTextField();
        tfSdtNT = new javax.swing.JTextField();
        btnThemTN = new javax.swing.JButton();
        btnSuaTN = new javax.swing.JButton();
        btnXoaTN = new javax.swing.JButton();
        pnTimKiemNV1 = new javax.swing.JPanel();
        lbTimKiemNV1 = new javax.swing.JLabel();
        tfTimKiemNT = new javax.swing.JTextField();
        spTimKiemNV1 = new javax.swing.JScrollPane();
        tbNT = new javax.swing.JTable();
        cbNT = new javax.swing.JComboBox<>();
        tfNgaySinhTN = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        tfIDNVTN = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbNVTN = new javax.swing.JTable();
        btnGioiTinhNhanVien = new javax.swing.ButtonGroup();
        pnTTNV = new javax.swing.JPanel();
        lbNV = new javax.swing.JLabel();
        pnTimKiemNV = new javax.swing.JPanel();
        lbTimKiemNV = new javax.swing.JLabel();
        tfTimKiem = new javax.swing.JTextField();
        spTimKiemNV = new javax.swing.JScrollPane();
        tbNV = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        lbIDNV = new javax.swing.JLabel();
        tfIDNV = new javax.swing.JTextField();
        tfTenNV = new javax.swing.JTextField();
        lbTenNV = new javax.swing.JLabel();
        lbGioiTinh = new javax.swing.JLabel();
        lbNgaySinh = new javax.swing.JLabel();
        tfSDT = new javax.swing.JTextField();
        lbSDT = new javax.swing.JLabel();
        tfDiaChi = new javax.swing.JTextField();
        lbDiaChi = new javax.swing.JLabel();
        tfCMND = new javax.swing.JTextField();
        lbCMND = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        lbEmail = new javax.swing.JLabel();
        lbBangCap = new javax.swing.JLabel();
        lbChucVu = new javax.swing.JLabel();
        lbPhongBan = new javax.swing.JLabel();
        lbLuongBong = new javax.swing.JLabel();
        tfLuongBong = new javax.swing.JTextField();
        lbPhuCap = new javax.swing.JLabel();
        tfPhuCap = new javax.swing.JTextField();
        lbSoNNNV = new javax.swing.JLabel();
        tfSongaynghi = new javax.swing.JTextField();
        lbTinhTrang = new javax.swing.JLabel();
        rbtnNam = new javax.swing.JRadioButton();
        rbtnNu = new javax.swing.JRadioButton();
        cbbPhongBan = new javax.swing.JComboBox<>();
        cbbBangCap = new javax.swing.JComboBox<>();
        cbbChucVu = new javax.swing.JComboBox<>();
        cbbTinhTrang = new javax.swing.JComboBox<>();
        lbImageNV = new javax.swing.JLabel();
        btnChonAnh = new javax.swing.JButton();
        btnThemNV = new javax.swing.JButton();
        btnXoaNV = new javax.swing.JButton();
        btnSuaNV = new javax.swing.JButton();
        btnNhanThan = new javax.swing.JButton();
        dcNgaySinh = new com.toedter.calendar.JDateChooser();

        FrameNhanThan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FrameNhanThanMousePressed(evt);
            }
        });

        lbTTNT.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbTTNT.setText("Thông tin người thân");

        lbNVNT.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lbNVNT.setText("Nhân viên");

        lbMoiQuanHe.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lbMoiQuanHe.setText("Mối quan hệ");

        lbHTNT.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lbHTNT.setText("Họ tên Người thân");

        lbSdtNT.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lbSdtNT.setText("Số điện thoại");

        lbNSNT.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lbNSNT.setText("Ngày sinh");

        tfHTNT.setFont(new java.awt.Font("Segoe UI Light", 1, 13)); // NOI18N
        tfHTNT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHTNTActionPerformed(evt);
            }
        });

        tfNVNT.setFont(new java.awt.Font("Segoe UI Light", 1, 13)); // NOI18N
        tfNVNT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNVNTActionPerformed(evt);
            }
        });

        tfMoiQuanHe.setFont(new java.awt.Font("Segoe UI Light", 1, 13)); // NOI18N
        tfMoiQuanHe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMoiQuanHeActionPerformed(evt);
            }
        });

        tfSdtNT.setFont(new java.awt.Font("Segoe UI Light", 1, 13)); // NOI18N
        tfSdtNT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSdtNTActionPerformed(evt);
            }
        });

        btnThemTN.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnThemTN.setText("Thêm");
        btnThemTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTNActionPerformed(evt);
            }
        });

        btnSuaTN.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnSuaTN.setText("Sửa");
        btnSuaTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaTNActionPerformed(evt);
            }
        });

        btnXoaTN.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnXoaTN.setText("Xóa");
        btnXoaTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTNActionPerformed(evt);
            }
        });

        pnTimKiemNV1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnTimKiemNV1.setPreferredSize(new java.awt.Dimension(1089, 200));

        lbTimKiemNV1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lbTimKiemNV1.setText("Tìm kiếm");

        tfTimKiemNT.setFont(new java.awt.Font("Segoe UI Light", 1, 13)); // NOI18N
        tfTimKiemNT.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfTimKiemNTCaretUpdate(evt);
            }
        });

        tbNT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Họ tên người thân", "Tên nhân viên", "Mối quan hệ", "Số điện thoại"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbNT.setRowHeight(25);
        tbNT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbNTMousePressed(evt);
            }
        });
        spTimKiemNV1.setViewportView(tbNT);

        cbNT.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        cbNT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "ID", "Họ tên người thân", "Mối quan hệ", "Số điện thoại" }));

        javax.swing.GroupLayout pnTimKiemNV1Layout = new javax.swing.GroupLayout(pnTimKiemNV1);
        pnTimKiemNV1.setLayout(pnTimKiemNV1Layout);
        pnTimKiemNV1Layout.setHorizontalGroup(
            pnTimKiemNV1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiemNV1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbTimKiemNV1)
                .addGap(18, 18, 18)
                .addComponent(tfTimKiemNT, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbNT, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnTimKiemNV1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spTimKiemNV1)
                .addContainerGap())
        );
        pnTimKiemNV1Layout.setVerticalGroup(
            pnTimKiemNV1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiemNV1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTimKiemNV1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnTimKiemNV1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbTimKiemNV1)
                        .addComponent(tfTimKiemNT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbNT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(spTimKiemNV1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );

        tfNgaySinhTN.setDateFormatString("yyyy-MM-dd");
        tfNgaySinhTN.setMaxSelectableDate(new java.util.Date(253370743265000L));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel1.setText("ID_ Nhân viên");

        tbNVTN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID_Nhân viên", "Tên nhân viên"
            }
        ));
        tbNVTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbNVTNMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbNVTN);

        javax.swing.GroupLayout FrameNhanThanLayout = new javax.swing.GroupLayout(FrameNhanThan.getContentPane());
        FrameNhanThan.getContentPane().setLayout(FrameNhanThanLayout);
        FrameNhanThanLayout.setHorizontalGroup(
            FrameNhanThanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameNhanThanLayout.createSequentialGroup()
                .addGroup(FrameNhanThanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrameNhanThanLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(FrameNhanThanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FrameNhanThanLayout.createSequentialGroup()
                                .addGroup(FrameNhanThanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbHTNT)
                                    .addComponent(lbNVNT)
                                    .addComponent(lbNSNT))
                                .addGap(21, 21, 21)
                                .addGroup(FrameNhanThanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfHTNT, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNgaySinhTN, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(FrameNhanThanLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(54, 54, 54)
                                .addGroup(FrameNhanThanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfNVNT, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfIDNVTN, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(FrameNhanThanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FrameNhanThanLayout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addGroup(FrameNhanThanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbMoiQuanHe)
                                    .addComponent(lbSdtNT))
                                .addGap(44, 44, 44)
                                .addGroup(FrameNhanThanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfSdtNT, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfMoiQuanHe, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(FrameNhanThanLayout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(btnThemTN)
                                .addGap(37, 37, 37)
                                .addComponent(btnSuaTN)
                                .addGap(38, 38, 38)
                                .addComponent(btnXoaTN))))
                    .addGroup(FrameNhanThanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbTTNT)))
                .addContainerGap(78, Short.MAX_VALUE))
            .addComponent(pnTimKiemNV1, javax.swing.GroupLayout.DEFAULT_SIZE, 998, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameNhanThanLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(233, 233, 233))
        );
        FrameNhanThanLayout.setVerticalGroup(
            FrameNhanThanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameNhanThanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTTNT)
                .addGap(18, 18, 18)
                .addGroup(FrameNhanThanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(FrameNhanThanLayout.createSequentialGroup()
                        .addGroup(FrameNhanThanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbMoiQuanHe)
                            .addComponent(tfMoiQuanHe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(tfIDNVTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(FrameNhanThanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSdtNT)
                            .addComponent(tfSdtNT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNVNT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbNVNT))
                .addGap(18, 18, 18)
                .addGroup(FrameNhanThanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbNSNT)
                    .addGroup(FrameNhanThanLayout.createSequentialGroup()
                        .addGroup(FrameNhanThanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(FrameNhanThanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnThemTN)
                                .addComponent(btnSuaTN)
                                .addComponent(btnXoaTN))
                            .addGroup(FrameNhanThanLayout.createSequentialGroup()
                                .addGroup(FrameNhanThanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbHTNT)
                                    .addComponent(tfHTNT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(tfNgaySinhTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(5, 5, 5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnTimKiemNV1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
        );

        pnTTNV.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbNV.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        lbNV.setText("Thông tin nhân viên");

        pnTimKiemNV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnTimKiemNV.setPreferredSize(new java.awt.Dimension(1089, 200));

        lbTimKiemNV.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lbTimKiemNV.setText("Tìm kiếm");

        tfTimKiem.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N

        tbNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên nhân viên", "Giới tính", "Ngày sinh", "Số điện thoại", "Email", "Tình trạng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbNV.setRowHeight(25);
        spTimKiemNV.setViewportView(tbNV);
        if (tbNV.getColumnModel().getColumnCount() > 0) {
            tbNV.getColumnModel().getColumn(0).setMinWidth(80);
            tbNV.getColumnModel().getColumn(0).setMaxWidth(80);
            tbNV.getColumnModel().getColumn(2).setMinWidth(120);
            tbNV.getColumnModel().getColumn(2).setMaxWidth(120);
        }

        jComboBox1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "ID", "Tên nhân viên", "Giới tính", "Ngày sinh", "Số điện thoại", "Email", "Tình trạng" }));
        jComboBox1.setPreferredSize(new java.awt.Dimension(81, 29));

        javax.swing.GroupLayout pnTimKiemNVLayout = new javax.swing.GroupLayout(pnTimKiemNV);
        pnTimKiemNV.setLayout(pnTimKiemNVLayout);
        pnTimKiemNVLayout.setHorizontalGroup(
            pnTimKiemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiemNVLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbTimKiemNV)
                .addGap(18, 18, 18)
                .addComponent(tfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnTimKiemNVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spTimKiemNV)
                .addContainerGap())
        );
        pnTimKiemNVLayout.setVerticalGroup(
            pnTimKiemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiemNVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTimKiemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(pnTimKiemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbTimKiemNV)
                        .addComponent(tfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spTimKiemNV, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lbIDNV.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lbIDNV.setText("Mã nhân viên");

        tfIDNV.setFont(new java.awt.Font("Segoe UI Light", 1, 13)); // NOI18N
        tfIDNV.setMinimumSize(new java.awt.Dimension(64, 28));
        tfIDNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIDNVActionPerformed(evt);
            }
        });

        tfTenNV.setFont(new java.awt.Font("Segoe UI Light", 1, 13)); // NOI18N
        tfTenNV.setMinimumSize(new java.awt.Dimension(64, 28));
        tfTenNV.setPreferredSize(new java.awt.Dimension(64, 28));
        tfTenNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTenNVActionPerformed(evt);
            }
        });

        lbTenNV.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lbTenNV.setText("Tên nhân viên");

        lbGioiTinh.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lbGioiTinh.setText("Giới tính");

        lbNgaySinh.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lbNgaySinh.setText("Ngày sinh");

        tfSDT.setFont(new java.awt.Font("Segoe UI Light", 1, 13)); // NOI18N
        tfSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSDTActionPerformed(evt);
            }
        });

        lbSDT.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lbSDT.setText("Số điện thoại");

        tfDiaChi.setFont(new java.awt.Font("Segoe UI Light", 1, 13)); // NOI18N
        tfDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDiaChiActionPerformed(evt);
            }
        });

        lbDiaChi.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lbDiaChi.setText("Địa chỉ");

        tfCMND.setFont(new java.awt.Font("Segoe UI Light", 1, 13)); // NOI18N
        tfCMND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCMNDActionPerformed(evt);
            }
        });

        lbCMND.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lbCMND.setText("CMND/CCCD");

        tfEmail.setFont(new java.awt.Font("Segoe UI Light", 1, 13)); // NOI18N
        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });

        lbEmail.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lbEmail.setText("Email");

        lbBangCap.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lbBangCap.setText("Bằng cấp");

        lbChucVu.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lbChucVu.setText("Chức vụ");

        lbPhongBan.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lbPhongBan.setText("Phòng ban");

        lbLuongBong.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lbLuongBong.setText("Lương bổng");

        tfLuongBong.setFont(new java.awt.Font("Segoe UI Light", 1, 13)); // NOI18N
        tfLuongBong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLuongBongActionPerformed(evt);
            }
        });

        lbPhuCap.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lbPhuCap.setText("Phụ cấp");

        tfPhuCap.setFont(new java.awt.Font("Segoe UI Light", 1, 13)); // NOI18N
        tfPhuCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPhuCapActionPerformed(evt);
            }
        });

        lbSoNNNV.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lbSoNNNV.setText("Số ngày nghỉ");

        tfSongaynghi.setFont(new java.awt.Font("Segoe UI Light", 1, 13)); // NOI18N
        tfSongaynghi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSongaynghiActionPerformed(evt);
            }
        });

        lbTinhTrang.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lbTinhTrang.setText("Tình trạng");

        rbtnNam.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        rbtnNam.setText("Nam");
        rbtnNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnNamActionPerformed(evt);
            }
        });

        rbtnNu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        rbtnNu.setText("Nữ");

        cbbTinhTrang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Còn làm việc", "Đã nghỉ làm" }));
        cbbTinhTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTinhTrangActionPerformed(evt);
            }
        });

        lbImageNV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnChonAnh.setText("Chọn ảnh");
        btnChonAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonAnhActionPerformed(evt);
            }
        });

        btnThemNV.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnThemNV.setText("Thêm");
        btnThemNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNVActionPerformed(evt);
            }
        });

        btnXoaNV.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnXoaNV.setText("Xóa");
        btnXoaNV.setEnabled(false);
        btnXoaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNVActionPerformed(evt);
            }
        });

        btnSuaNV.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnSuaNV.setText("Sửa");
        btnSuaNV.setEnabled(false);
        btnSuaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaNVActionPerformed(evt);
            }
        });

        btnNhanThan.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnNhanThan.setText("Nhân thân");
        btnNhanThan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanThanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnTTNVLayout = new javax.swing.GroupLayout(pnTTNV);
        pnTTNV.setLayout(pnTTNVLayout);
        pnTTNVLayout.setHorizontalGroup(
            pnTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTTNVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTTNVLayout.createSequentialGroup()
                        .addComponent(pnTimKiemNV, javax.swing.GroupLayout.DEFAULT_SIZE, 1084, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pnTTNVLayout.createSequentialGroup()
                        .addGroup(pnTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNV)
                            .addGroup(pnTTNVLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(pnTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnTTNVLayout.createSequentialGroup()
                                            .addGroup(pnTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lbIDNV)
                                                .addComponent(lbTenNV))
                                            .addGap(21, 21, 21)
                                            .addGroup(pnTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tfTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tfIDNV, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(pnTTNVLayout.createSequentialGroup()
                                            .addComponent(lbGioiTinh)
                                            .addGap(62, 62, 62)
                                            .addGroup(pnTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(pnTTNVLayout.createSequentialGroup()
                                                    .addComponent(rbtnNam, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(34, 34, 34)
                                                    .addComponent(rbtnNu, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(dcNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(pnTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(pnTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTTNVLayout.createSequentialGroup()
                                                    .addComponent(lbDiaChi)
                                                    .addGap(302, 302, 302))
                                                .addGroup(pnTTNVLayout.createSequentialGroup()
                                                    .addComponent(lbCMND)
                                                    .addGap(26, 26, 26)
                                                    .addComponent(tfCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(pnTTNVLayout.createSequentialGroup()
                                                .addComponent(lbEmail)
                                                .addGap(313, 313, 313)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTTNVLayout.createSequentialGroup()
                                            .addComponent(lbSDT)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tfSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTTNVLayout.createSequentialGroup()
                                            .addComponent(lbNgaySinh)
                                            .addGap(281, 281, 281))
                                        .addComponent(tfDiaChi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(pnTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnTTNVLayout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addComponent(btnNhanThan)
                                        .addGap(79, 79, 79)
                                        .addComponent(btnThemNV, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(63, 63, 63))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTTNVLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbBangCap)
                                            .addComponent(lbChucVu)
                                            .addComponent(lbPhongBan)
                                            .addComponent(lbLuongBong)
                                            .addComponent(lbPhuCap)
                                            .addComponent(lbSoNNNV)
                                            .addComponent(lbTinhTrang))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(pnTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(cbbTinhTrang, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(tfSongaynghi, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tfPhuCap, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tfLuongBong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(cbbBangCap, 0, 230, Short.MAX_VALUE)
                                            .addComponent(cbbChucVu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbbPhongBan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(4, 4, 4)))
                                .addGroup(pnTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnTTNVLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnSuaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(62, 62, 62)
                                        .addComponent(btnXoaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnTTNVLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(lbImageNV, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnTTNVLayout.createSequentialGroup()
                                        .addGap(89, 89, 89)
                                        .addComponent(btnChonAnh)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnTTNVLayout.setVerticalGroup(
            pnTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTTNVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTTNVLayout.createSequentialGroup()
                        .addComponent(lbImageNV, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnChonAnh))
                    .addGroup(pnTTNVLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(pnTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbIDNV)
                            .addComponent(tfIDNV, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(pnTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTenNV)
                            .addComponent(tfTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbGioiTinh)
                            .addComponent(rbtnNam)
                            .addComponent(rbtnNu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbNgaySinh)
                            .addComponent(dcNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSDT)
                            .addComponent(tfSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDiaChi))
                        .addGap(18, 18, 18)
                        .addGroup(pnTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbCMND))
                        .addGap(18, 18, 18)
                        .addGroup(pnTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEmail)))
                    .addGroup(pnTTNVLayout.createSequentialGroup()
                        .addGroup(pnTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbBangCap)
                            .addComponent(cbbBangCap, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbChucVu)
                            .addComponent(cbbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPhongBan)
                            .addComponent(cbbPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbLuongBong)
                            .addComponent(tfLuongBong, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPhuCap)
                            .addComponent(tfPhuCap, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSoNNNV)
                            .addComponent(tfSongaynghi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTinhTrang)
                            .addComponent(cbbTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSuaNV)
                            .addComponent(btnXoaNV)
                            .addComponent(btnThemNV)
                            .addComponent(btnNhanThan))))
                .addGap(18, 18, 18)
                .addComponent(pnTimKiemNV, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1096, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnTTNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnTTNV, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void rebuildFrame() {
        loadListNV();
        addMouseEvent();
    }
    
    /**
    * Xu ly su kien
    **/
    // <editor-fold defaultstate="collapsed" desc="Event Handling">  
    public void loadListNhanVienNhanThan() throws Exception{
        modelNVTN.setRowCount(0);
        NVDAO = new NhanVienDAO();
        ArrayList<NhanVienDTO> arrNV = NVDAO.getAllNV();
        for(int i=0;i<arrNV.size();i++){
            NhanVienDTO NV=arrNV.get(i);
            String id_nhanvien=NV.getId();
            String tennhanvien=NV.getName();
            Object[] row={id_nhanvien,tennhanvien};
            modelNVTN.addRow(row);
        }
    }
    
    
    public void loadListNhanThan(){ 
        modelTN.setRowCount(0);
        arrTN=TNBUS.getAllThanNhan();
        for(int i=0;i<arrTN.size();i++){
            ThanNhan_DTO tn=arrTN.get(i);
            int id=tn.getID_nguoithan();
            String tennhanvien=tn.getTennhanvien();
            String hoten=tn.getHoten();
            String moiquanhe= tn.getMoiquanhe();
            String sdt=tn.getSdt();
            Object[] row={id,hoten,tennhanvien,moiquanhe,sdt};
            modelTN.addRow(row);
        }
    }
        public void KhoiTaoBTN(){
        btnXoaTN.setEnabled(false);
        btnSuaTN.setEnabled(false);
    }
    
    
    
    
        
        
    private void loadListNV(){
        try {
            if (NhanVienBUS.dsnv == null || NhanVienBUS.dsnv.isEmpty()) new NhanVienBUS().docDSNV();
            if (BangCapBUS.dsbc == null || BangCapBUS.dsbc.isEmpty()) new BangCapBUS().docDSBC();
            if (ChucVu_BUS.dscv == null || ChucVu_BUS.dscv.isEmpty()) new ChucVu_BUS().docDSCV();
            if (PhongBanBUS.dspb == null || PhongBanBUS.dspb.isEmpty()) new PhongBanBUS().docDSPB();
            //Khởi tạo item bằng cấp
            for (BangCapDTO bc:BangCapBUS.dsbc) 
                cbbBangCap.addItem(bc.bangcap);
            for (ChucVu_DTO cv:ChucVu_BUS.dscv) 
                cbbChucVu.addItem(cv.tenchucvu);
            cbbPhongBan.addItem("");
            for (PhongBanDTO pb:PhongBanBUS.dspb) 
                cbbPhongBan.addItem(pb.tenphongban);
            //Khởi tạo item chức vụ
            //Khởi tạo table NV
            DefaultTableModel model = (DefaultTableModel) tbNV.getModel();
            for (NhanVienDTO nv:NhanVienBUS.dsnv) 
                if (nv.visible == 1) {
                    Vector row = new Vector();
                    row.add(nv.id); 
                    row.add(nv.name); 
                    if (nv.gioitinh == 1)
                    row.add("Nam"); else row.add("Nữ");
                    row.add(nv.ngaysinh); 
                    row.add(nv.sdt); 
                    row.add(nv.email); 
                    if (nv.tinhtrang == 1)
                    row.add("Còn làm việc"); else row.add("Đã nghỉ làm");
                    model.addRow(row);
                }
            tbNV.setModel(model);
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }
    
    private void resetForm() {
        tfIDNV.setText("");
        tfTenNV.setText("");
        rbtnNam.setSelected(false);
        rbtnNu.setSelected(false);
        dcNgaySinh.setCalendar(null);
        tfSDT.setText("");
        tfDiaChi.setText("");
        tfCMND.setText("");
        tfEmail.setText("");
        tfLuongBong.setText("0");
        tfPhuCap.setText("0");
        tfSongaynghi.setText("0");
        tbNV.getSelectionModel().clearSelection();
        lbImageNV.setIcon(null);
    }
    
    private void addMouseEvent() {
        //thêm event cho frame và table
        pnTTNV.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                resetForm();
                tfIDNV.setEnabled(true);
                btnSuaNV.setEnabled(false);
                btnXoaNV.setEnabled(false);
            }
        });
        pnTimKiemNV.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                resetForm();
                tfIDNV.setEnabled(true);
                btnSuaNV.setEnabled(false);
                btnXoaNV.setEnabled(false);
            }
        });
        tbNV.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                DefaultTableModel model = (DefaultTableModel) tbNV.getModel();
                int rowPos = tbNV.getSelectedRow();
                String idnv = model.getValueAt(rowPos, 0).toString();
                SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
                java.util.Date date;
                try {
                    date = format.parse(model.getValueAt(rowPos, 3).toString());
                    dcNgaySinh.setDate(date);
                } catch (ParseException ex) {
                    Logger.getLogger(NhanVienGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                tfIDNV.setText(idnv);
                tfTenNV.setText(model.getValueAt(rowPos, 1).toString());
                if (model.getValueAt(rowPos, 2).toString().equals("Nam")) {
                    rbtnNam.setSelected(true); 
                    rbtnNu.setSelected(false); 
                } else {
                    rbtnNam.setSelected(false);
                    rbtnNu.setSelected(true);
                }
                tfSDT.setText(model.getValueAt(rowPos, 4).toString());
                tfEmail.setText(model.getValueAt(rowPos, 5).toString());
                if (model.getValueAt(rowPos, 6).toString().equals("Còn làm việc"))
                    cbbTinhTrang.setSelectedIndex(0); else cbbTinhTrang.setSelectedIndex(1);
                for(NhanVienDTO nv:NhanVienBUS.dsnv) 
                    if (nv.id.equals(idnv)) {
                        tfDiaChi.setText(nv.diachi);
                        tfCMND.setText(nv.cmnd);
                        cbbBangCap.setSelectedIndex(nv.id_bangcap-1);
                        cbbChucVu.setSelectedIndex(nv.id_chucvu-1);
                        for(PhongBanDTO pb:PhongBanBUS.dspb)
                            if (pb.ID_phongban.equals(nv.id_phongban)) {
                                cbbPhongBan.setSelectedItem(pb.tenphongban);
                                break;
                            } else cbbPhongBan.setSelectedItem("");
                        tfLuongBong.setText(String.valueOf(nv.luong));
                        tfPhuCap.setText(String.valueOf(nv.phucap));
                        tfSongaynghi.setText(String.valueOf(nv.songaynghi));
                        //Set ảnh nhân viên được chọn
                        ImageIcon myimage = new ImageIcon(nv.hinhanh);
                        Image img = myimage.getImage();
                        Image resizeimg = img.getScaledInstance(lbImageNV.getWidth(), lbImageNV.getHeight(),Image.SCALE_SMOOTH);
                        lbImageNV.setIcon(new ImageIcon(resizeimg));
                    }
                tfIDNV.setEnabled(false);
                btnSuaNV.setEnabled(true);
                btnXoaNV.setEnabled(true);
            }
        });
    }
    
    private void tfIDNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIDNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIDNVActionPerformed

    private void tfTenNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTenNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTenNVActionPerformed

    private void tfSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSDTActionPerformed

    private void tfDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDiaChiActionPerformed

    private void tfCMNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCMNDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCMNDActionPerformed

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed

    private void tfLuongBongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLuongBongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLuongBongActionPerformed

    private void tfPhuCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPhuCapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPhuCapActionPerformed

    private void tfSongaynghiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSongaynghiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSongaynghiActionPerformed

    private void cbbTinhTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTinhTrangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbTinhTrangActionPerformed

    private void btnChonAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonAnhActionPerformed
        JFileChooser fc = new JFileChooser();
        File f;
//        fc.setCurrentDirectory(new File("G:\\Study\\Language Programming\\Java\\Thuc hanh\\qlnhansu_1.1\\images"));
        fc.showOpenDialog(null);
        f = fc.getSelectedFile();
        path = f.getAbsolutePath();
        ImageIcon myimage = new ImageIcon(path);
        Image img = myimage.getImage();
        Image resizeimg = img.getScaledInstance(lbImageNV.getWidth(), lbImageNV.getHeight(),Image.SCALE_SMOOTH);
        lbImageNV.setIcon(new ImageIcon(resizeimg));
    }//GEN-LAST:event_btnChonAnhActionPerformed

    private void btnThemNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNVActionPerformed
        if (checkField(1)) try {
            String id = tfIDNV.getText().trim();
            String name = tfTenNV.getText().trim();
            int cv = cbbChucVu.getSelectedIndex()+1;
            String idpb = "";
            for (PhongBanDTO pb:PhongBanBUS.dspb)
                if (pb.tenphongban.equals(cbbPhongBan.getSelectedItem().toString()))
                idpb = pb.ID_phongban;
            int bc = cbbBangCap.getSelectedIndex()+1;
            int gioitinh;
            if (rbtnNam.isSelected()) gioitinh = 1; else gioitinh = 0;
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            String date = format.format(dcNgaySinh.getDate()).toString();
            String sdt = tfSDT.getText();
            String email = tfEmail.getText();
            String cmnd = tfCMND.getText();
            if (tfLuongBong.getText().equals("")) tfLuongBong.setText("0");
            if (tfPhuCap.getText().equals("")) tfPhuCap.setText("0");
            if (tfSongaynghi.getText().equals("")) tfSongaynghi.setText("0");
            int luong = Integer.parseInt(tfLuongBong.getText());
            int phucap = Integer.parseInt(tfPhuCap.getText());
            int songaynghi = Integer.parseInt(tfSongaynghi.getText());
            String diachi = tfDiaChi.getText();
            String hinhanh = path;
            new NhanVienBUS().themNV(id, name, cv, idpb, bc, gioitinh, date, sdt, email, cmnd, luong, phucap, songaynghi, diachi, hinhanh);
            //reset lại table
            DefaultTableModel model = (DefaultTableModel) tbNV.getModel();
            for (int i=0; i<model.getRowCount(); i++)
                model.removeRow(i);
            loadListNV();
            resetForm();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnThemNVActionPerformed

    private void btnXoaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNVActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbNV.getModel();
        int rowPos = tbNV.getSelectedRow();
        int index = 0;
        String idnv = model.getValueAt(rowPos, 0).toString();
        try {
        for (int i=0; i<NhanVienBUS.dsnv.size(); i++) 
            if (idnv.equals(NhanVienBUS.dsnv.get(i).id)) {
                index = i;
                break;
            }
        new NhanVienBUS().xoaNV(idnv, index);
        //reset lại table
        for (int i=0; i<model.getRowCount(); i++)
            model.removeRow(i);
        loadListNV();
        resetForm();
        } catch (Exception ex) {
            Logger.getLogger(NhanVienGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnXoaNVActionPerformed

    private void btnSuaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaNVActionPerformed
        if (checkField(2)) try {
            DefaultTableModel model = (DefaultTableModel) tbNV.getModel();
            //lấy idnv đang được chọn và lấy vị trí của nhân viên đó trong ArrayList DSNV
            String idnv = model.getValueAt(tbNV.getSelectedRow(), 0).toString().trim();
            int index = 0;
            for (int i=0; i<NhanVienBUS.dsnv.size(); i++) 
            if (idnv.equals(NhanVienBUS.dsnv.get(i).id)) {
                index = i;
                break;
            }
            String name = tfTenNV.getText().trim();
            int cv = cbbChucVu.getSelectedIndex()+1;
            String idpb = "";
            for (PhongBanDTO pb:PhongBanBUS.dspb)
                if (pb.tenphongban.equals(cbbPhongBan.getSelectedItem().toString()))
                idpb = pb.ID_phongban;
            int bc = cbbBangCap.getSelectedIndex()+1;
            int gioitinh;
            if (rbtnNam.isSelected()) gioitinh = 1; else gioitinh = 0;
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            String date = format.format(dcNgaySinh.getDate()).toString();
            String sdt = tfSDT.getText();
            String email = tfEmail.getText();
            String cmnd = tfCMND.getText();
            if (tfLuongBong.getText().equals("")) tfLuongBong.setText("0");
            if (tfPhuCap.getText().equals("")) tfPhuCap.setText("0");
            if (tfSongaynghi.getText().equals("")) tfSongaynghi.setText("0");
            int luong = Integer.parseInt(tfLuongBong.getText());
            int phucap = Integer.parseInt(tfPhuCap.getText());
            int songaynghi = Integer.parseInt(tfSongaynghi.getText());
            int tinhtrang;
            if (cbbTinhTrang.getSelectedItem().toString().equals("Còn làm việc")) tinhtrang = 1; else tinhtrang = 0;
            String diachi = tfDiaChi.getText();
            String hinhanh = path;
            new NhanVienBUS().suaNV(index, name, cv, idpb, bc, gioitinh, date, sdt, email, cmnd, luong, phucap, songaynghi, diachi, tinhtrang, hinhanh);
            //reset lại table
            for (int i=0; i<model.getRowCount(); i++)
                model.removeRow(i);
            loadListNV();
            resetForm();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnSuaNVActionPerformed

    private void btnNhanThanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanThanActionPerformed
        FrameNhanThan.pack();
        FrameNhanThan.setVisible(true);
        modelTN=(DefaultTableModel) tbNT.getModel();
        loadListNhanThan();
    }//GEN-LAST:event_btnNhanThanActionPerformed

    private void tfHTNTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHTNTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHTNTActionPerformed

    private void tfNVNTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNVNTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNVNTActionPerformed

    private void tfMoiQuanHeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMoiQuanHeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMoiQuanHeActionPerformed

    private void tfSdtNTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSdtNTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSdtNTActionPerformed

    private void btnThemTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTNActionPerformed
      try{
        if(tfIDNVTN.getText().trim().equals("")||
           tfNVNT.getText().trim().equals("")||
           tfHTNT.getText().trim().equals("")||
           tfMoiQuanHe.getText().trim().equals("")||
           tfSdtNT.getText().trim().equals("") ){
           JOptionPane.showMessageDialog(this,"Vui lòng nhập đủ thông tin");
        }else{
           SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
           String getdate = format.format(tfNgaySinhTN.getDate());
           ThanNhan_DTO tn=new ThanNhan_DTO();
           tn.setID_nhanvien(tfIDNVTN.getText());
           tn.setTennhanvien(tfNVNT.getText());
           tn.setHoten(tfHTNT.getText());
           tn.setMoiquanhe(tfMoiQuanHe.getText());
           tn.setNgaysinh(getdate);
           tn.setSdt(tfSdtNT.getText());
           JOptionPane.showMessageDialog(this, TNBUS.addThanNhan(tn));
           loadListNhanThan();
        }
    }catch(Exception ex){
        JOptionPane.showMessageDialog(this, "Thêm thất bại");
        }
    }//GEN-LAST:event_btnThemTNActionPerformed

    private void btnXoaTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTNActionPerformed
       int i=tbNT.getSelectedRow();
       try{
       if(i>=0){
       JOptionPane.showMessageDialog(this, TNBUS.delThanNhan((int) tbNT.getValueAt(i,0)));
       tfIDNVTN.setText("");
       tfNVNT.setText("");
       tfHTNT.setText("");
       tfMoiQuanHe.setText("");
       tfSdtNT.setText("");
       Date date=null;
       tfNgaySinhTN.setDate(date);
       }
       else{
           JOptionPane.showMessageDialog(this,"Vui lòng chọn thân nhân để xóa");
       }
       loadListNhanThan();
       }catch(Exception ex){
           JOptionPane.showMessageDialog(this, "Xóa thất bại");
       }
       btnXoaTN.setEnabled(false);
       btnSuaTN.setEnabled(false);
    }//GEN-LAST:event_btnXoaTNActionPerformed

    private void btnSuaTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaTNActionPerformed
         try{
        if(tfIDNVTN.getText().trim().equals("")||
           tfNVNT.getText().trim().equals("")||
           tfHTNT.getText().trim().equals("")||
           tfMoiQuanHe.getText().trim().equals("")||
           tfSdtNT.getText().trim().equals("")){
           JOptionPane.showMessageDialog(this,"Vui lòng nhập đủ thông tin");
        }else{
           SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
           String getdate = format.format(tfNgaySinhTN.getDate());
           int idnt = Integer.parseInt(tbNT.getValueAt(tbNT.getSelectedRow(), 0).toString());
           ThanNhan_DTO tn=new ThanNhan_DTO();
           tn.setID_nguoithan(idnt);
           tn.setID_nhanvien(tfIDNVTN.getText());
           tn.setTennhanvien(tfNVNT.getText());
           tn.setHoten(tfHTNT.getText());
           tn.setMoiquanhe(tfMoiQuanHe.getText());
           tn.setNgaysinh(getdate);
           tn.setSdt(tfSdtNT.getText());
            System.out.println(tn.getID_nguoithan());
           JOptionPane.showMessageDialog(this, TNBUS.suaThanNhan(tn));
           loadListNhanThan();
        }
    }catch(Exception ex){
        JOptionPane.showMessageDialog(this, "Sửa thất bại");
        }
        btnXoaTN.setEnabled(false);
        btnSuaTN.setEnabled(false); 
    }//GEN-LAST:event_btnSuaTNActionPerformed

    private void tfTimKiemNTCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfTimKiemNTCaretUpdate
        modelTN.setRowCount(0);
        try{
        if(!tfTimKiemNT.getText().trim().equals("")){
        String st=tfTimKiemNT.getText();
        int select=0;
        if(cbNT.getSelectedItem().equals("ID")){
                select=Integer.parseInt(tfTimKiemNT.getText());
                arrTN=TNBUS.TimKiemThanNhan(st,select,0);
            }
        if(cbNT.getSelectedItem().equals("Họ tên người thân")){
                arrTN=TNBUS.TimKiemThanNhan(st,select,1);
            }
        
        if(cbNT.getSelectedItem().equals("Mối quan hệ")){
                arrTN=TNBUS.TimKiemThanNhan(st,select,2);
        }
        if(cbNT.getSelectedItem().equals("Số điện thoại")){
                arrTN=TNBUS.TimKiemThanNhan(st,select,3);
        }

        if(cbNT.getSelectedItem().equals("Tất cả")){
               try{
                    select=Integer.parseInt(tfTimKiemNT.getText());
                }catch(NumberFormatException e){
                    select=0;
                }
                arrTN=TNBUS.TimKiemThanNhan(st,select,4);           
        }
        for(int i=0;i<arrTN.size();i++){
            ThanNhan_DTO tn=arrTN.get(i);
            int id=tn.getID_nguoithan();
            String tennhanvien=tn.getTennhanvien();
            String hoten=tn.getHoten();
            String moiquanhe= tn.getMoiquanhe();
            String sdt=tn.getSdt();
            Object[] row={id,hoten,tennhanvien,moiquanhe,sdt};
            modelTN.addRow(row);
            }
        }
        else{
            loadListNhanThan();
        }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_tfTimKiemNTCaretUpdate

    private void FrameNhanThanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameNhanThanMousePressed
       KhoiTaoBTN();
       tbNT.getSelectionModel().clearSelection();
       tbNVTN.getSelectionModel().clearSelection();
    }//GEN-LAST:event_FrameNhanThanMousePressed

    private void tbNTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNTMousePressed
        btnXoaTN.setEnabled(true);
        btnSuaTN.setEnabled(true);
        int id=(int) tbNT.getValueAt(tbNT.getSelectedRow(), 0);
        ThanNhan_DTO TN= TNBUS.HienThiNT(id);
        Date date = null;
        try {
            date = new SimpleDateFormat("yyyy-MM-dd").parse(TN.getNgaysinh());
        } catch (ParseException ex) {
            java.util.logging.Logger.getLogger(NhanVienGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        tfIDNVTN.setText(TN.getID_nhanvien()+"");
        tfNVNT.setText(TN.getTennhanvien());
        tfHTNT.setText(TN.getHoten());
        tfMoiQuanHe.setText(TN.getMoiquanhe());
        tfNgaySinhTN.setDate(date);
        tfSdtNT.setText(TN.getSdt()+"");
    }//GEN-LAST:event_tbNTMousePressed

    private void tbNVTNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNVTNMousePressed
        tfIDNVTN.setText((String) tbNVTN.getValueAt(tbNVTN.getSelectedRow(),0));
        tfNVNT.setText((String) tbNVTN.getValueAt(tbNVTN.getSelectedRow(),1));
        tfHTNT.setText("");
        tfMoiQuanHe.setText("");
        tfSdtNT.setText("");
        Date date=null;
        tfNgaySinhTN.setDate(date);
    }//GEN-LAST:event_tbNVTNMousePressed

    private void rbtnNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnNamActionPerformed

    private boolean checkField(int choice) {
        if (choice == 1) {
            if (tfIDNV.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập mã nhân viên", "Lỗi dữ liệu", JOptionPane.ERROR_MESSAGE);
                return false;
            }
            if (tfTenNV.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập tên nhân viên", "Lỗi dữ liệu", JOptionPane.ERROR_MESSAGE);
                return false;
            }
            if (rbtnNam.isSelected() == false && rbtnNu.isSelected() == false) {
                JOptionPane.showMessageDialog(null, "Vui lòng chọn giới tính", "Lỗi dữ liệu", JOptionPane.ERROR_MESSAGE);
                return false;
            }
            if (dcNgaySinh.getDate() == null) {
                JOptionPane.showMessageDialog(null, "Vui lòng chọn ngày sinh", "Lỗi dữ liệu", JOptionPane.ERROR_MESSAGE);
                return false;
            }
            if (tfCMND.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập số CMND", "Lỗi dữ liệu", JOptionPane.ERROR_MESSAGE);
                return false;
            }
            if (tfEmail.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập email", "Lỗi dữ liệu", JOptionPane.ERROR_MESSAGE);
                return false;
            }
            if (!tfIDNV.getText().trim().equals("") || !tfCMND.getText().trim().equals("") || !tfEmail.getText().trim().equals("")) {
                //kiểm tra tính hợp lệ của cmnd 
                try {
                    long cmnd = Long.parseLong(tfCMND.getText());
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "CMND không hợp lệ!!", "Lỗi dữ liệu", JOptionPane.ERROR_MESSAGE);
                    return false;
                }
                if (!(tfCMND.getText().length() == 12)) {
                    JOptionPane.showMessageDialog(null, "CMND phải gồm 12 chữ số (0-9)!!", "Lỗi dữ liệu", JOptionPane.ERROR_MESSAGE);
                    return false;
                }
                //kiểm tra tính hợp lệ của email
                Matcher matcher = VALID_EMAIL_ADDRESS_REGEX.matcher(tfEmail.getText().trim());
                if (!matcher.find()) {
                    JOptionPane.showMessageDialog(null, "Email bị không hợp lệ\nVui lòng nhập lại Email!!", "Lỗi dữ liệu", JOptionPane.ERROR_MESSAGE);
                    return false;
                }
                
                //kiểm tra trùng id, cmnd, email
                for (NhanVienDTO nv:NhanVienBUS.dsnv) {
                    if (tfIDNV.getText().trim().equalsIgnoreCase(nv.id)) {
                        JOptionPane.showMessageDialog(null, "ID nhân viên bị trùng, vui lòng nhập lại!!", "Lỗi dữ liệu", JOptionPane.ERROR_MESSAGE);
                        return false;
                    }
                    if (tfCMND.getText().trim().equalsIgnoreCase(nv.cmnd)) {
                        JOptionPane.showMessageDialog(null, "CMND bị trùng, vui lòng nhập lại!!", "Lỗi dữ liệu", JOptionPane.ERROR_MESSAGE);
                        return false;
                    }
                    if (tfEmail.getText().trim().equalsIgnoreCase(nv.email)) {
                        JOptionPane.showMessageDialog(null, "Email đã được sử dụng!!", "Lỗi dữ liệu", JOptionPane.ERROR_MESSAGE);
                        return false;
                    }
                }
            }
        }
        
        if (choice == 2) {
            if (tfTenNV.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập tên nhân viên", "Lỗi dữ liệu", JOptionPane.ERROR_MESSAGE);
                return false;
            }
            if (dcNgaySinh.getDate() == null) {
                JOptionPane.showMessageDialog(null, "Vui lòng chọn ngày sinh", "Lỗi dữ liệu", JOptionPane.ERROR_MESSAGE);
                return false;
            }
            if (tfCMND.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập số CMND", "Lỗi dữ liệu", JOptionPane.ERROR_MESSAGE);
                return false;
            }
            if (tfEmail.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập email", "Lỗi dữ liệu", JOptionPane.ERROR_MESSAGE);
                return false;
            }
            if (!tfIDNV.getText().trim().equals("") || !tfCMND.getText().trim().equals("") || !tfEmail.getText().trim().equals("")) {
                //kiểm tra tính hợp lệ của cmnd 
                try {
                    long cmnd = Long.parseLong(tfCMND.getText());
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "CMND không hợp lệ!!", "Lỗi dữ liệu", JOptionPane.ERROR_MESSAGE);
                    return false;
                }
                if (!(tfCMND.getText().length() == 12)) {
                    JOptionPane.showMessageDialog(null, "CMND không hợp lệ!!", "Lỗi dữ liệu", JOptionPane.ERROR_MESSAGE);
                    return false;
                }
                //kiểm tra tính hợp lệ của email
                Matcher matcher = VALID_EMAIL_ADDRESS_REGEX.matcher(tfEmail.getText().trim());
                if (!matcher.find()) {
                    JOptionPane.showMessageDialog(null, "Email bị không hợp lệ\nVui lòng nhập lại Email!!", "Lỗi dữ liệu", JOptionPane.ERROR_MESSAGE);
                    return false;
                }
                
                //kiểm tra trùng id, cmnd, email
                for (NhanVienDTO nv:NhanVienBUS.dsnv) {
                    //bỏ qua phần kiểm tra trùng nhân viên đang được chọn
                    if (!tfIDNV.getText().trim().equalsIgnoreCase(nv.id)) {
                        if (tfCMND.getText().trim().equalsIgnoreCase(nv.cmnd)) {
                            JOptionPane.showMessageDialog(null, "CMND bị trùng, vui lòng nhập lại!!", "Lỗi dữ liệu", JOptionPane.ERROR_MESSAGE);
                            return false;
                        }
                        if (tfEmail.getText().trim().equalsIgnoreCase(nv.email)) {
                            JOptionPane.showMessageDialog(null, "Email đã được sử dụng!!", "Lỗi dữ liệu", JOptionPane.ERROR_MESSAGE);
                            return false;
                        }
                    }
                }
            }
        }
        return true;
    }
    
// </editor-fold>  

    // <editor-fold defaultstate="collapsed" desc="Variables Declaration">  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame FrameNhanThan;
    private javax.swing.JButton btnChonAnh;
    private javax.swing.ButtonGroup btnGioiTinhNhanVien;
    private javax.swing.JButton btnNhanThan;
    private javax.swing.JButton btnSuaNV;
    private javax.swing.JButton btnSuaTN;
    private javax.swing.JButton btnThemNV;
    private javax.swing.JButton btnThemTN;
    private javax.swing.JButton btnXoaNV;
    private javax.swing.JButton btnXoaTN;
    private javax.swing.JComboBox<String> cbNT;
    private javax.swing.JComboBox<String> cbbBangCap;
    private javax.swing.JComboBox<String> cbbChucVu;
    private javax.swing.JComboBox<String> cbbPhongBan;
    private javax.swing.JComboBox<String> cbbTinhTrang;
    private com.toedter.calendar.JDateChooser dcNgaySinh;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbBangCap;
    private javax.swing.JLabel lbCMND;
    private javax.swing.JLabel lbChucVu;
    private javax.swing.JLabel lbDiaChi;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbGioiTinh;
    private javax.swing.JLabel lbHTNT;
    private javax.swing.JLabel lbIDNV;
    private javax.swing.JLabel lbImageNV;
    private javax.swing.JLabel lbLuongBong;
    private javax.swing.JLabel lbMoiQuanHe;
    private javax.swing.JLabel lbNSNT;
    private javax.swing.JLabel lbNV;
    private javax.swing.JLabel lbNVNT;
    private javax.swing.JLabel lbNgaySinh;
    private javax.swing.JLabel lbPhongBan;
    private javax.swing.JLabel lbPhuCap;
    private javax.swing.JLabel lbSDT;
    private javax.swing.JLabel lbSdtNT;
    private javax.swing.JLabel lbSoNNNV;
    private javax.swing.JLabel lbTTNT;
    private javax.swing.JLabel lbTenNV;
    private javax.swing.JLabel lbTimKiemNV;
    private javax.swing.JLabel lbTimKiemNV1;
    private javax.swing.JLabel lbTinhTrang;
    private javax.swing.JPanel pnTTNV;
    private javax.swing.JPanel pnTimKiemNV;
    private javax.swing.JPanel pnTimKiemNV1;
    private javax.swing.JRadioButton rbtnNam;
    private javax.swing.JRadioButton rbtnNu;
    private javax.swing.JScrollPane spTimKiemNV;
    private javax.swing.JScrollPane spTimKiemNV1;
    private javax.swing.JTable tbNT;
    private javax.swing.JTable tbNV;
    private javax.swing.JTable tbNVTN;
    private javax.swing.JTextField tfCMND;
    private javax.swing.JTextField tfDiaChi;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfHTNT;
    private javax.swing.JTextField tfIDNV;
    private javax.swing.JTextField tfIDNVTN;
    private javax.swing.JTextField tfLuongBong;
    private javax.swing.JTextField tfMoiQuanHe;
    private javax.swing.JTextField tfNVNT;
    private com.toedter.calendar.JDateChooser tfNgaySinhTN;
    private javax.swing.JTextField tfPhuCap;
    private javax.swing.JTextField tfSDT;
    private javax.swing.JTextField tfSdtNT;
    private javax.swing.JTextField tfSongaynghi;
    private javax.swing.JTextField tfTenNV;
    private javax.swing.JTextField tfTimKiem;
    private javax.swing.JTextField tfTimKiemNT;
    // End of variables declaration//GEN-END:variables
    // </editor-fold> 
}
