package GUI;

import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Toolkit;

public class qlns extends javax.swing.JFrame {

    NhanVienGUI pnThongTinNhanVien;
    HopDongGUI pnTTHD;
    ViPhamGUI pnThongTinViPham;
    DonNghiPhepGUI pnDonNghiPhep;
    LuongGUI pnLuongNV;
    PhongBanGUI pnPhongBan;
    DuAnGUI pnDuAn;
    ThongKeGUI pnThongKe;
    
    
    public qlns() {
        initComponents();
        initChildComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameThongtindoan = new javax.swing.JDialog();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        tbpFrame = new javax.swing.JTabbedPane();
        tabNhanVien = new javax.swing.JPanel();
        tabHopDong = new javax.swing.JPanel();
        tabViPham = new javax.swing.JPanel();
        tabDonNghiPhep = new javax.swing.JPanel();
        tabLuong = new javax.swing.JPanel();
        tabPhongBan = new javax.swing.JPanel();
        tabDuAn = new javax.swing.JPanel();
        tabThongKe = new javax.swing.JPanel();
        btnTTPM = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();

        jLabel91.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel91.setText("Thông tin đồ án");

        jLabel92.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel92.setText("Tên nhóm:");

        jLabel93.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel93.setText("Thành viên thực hiện:");

        jLabel94.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel94.setForeground(new java.awt.Color(255, 0, 0));
        jLabel94.setText("Huỳnh Cẩm Cơ");

        jLabel95.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel95.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel95.setText("Ngày hoàn thành");
        jLabel95.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel96.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel96.setText("Môn học: lập trình Java");

        jLabel97.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel97.setText("Năm học: 2021 - 2022 học kì 2");

        jLabel99.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel99.setText("Ngày bắt đầu thực hiện");

        jLabel100.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel100.setForeground(new java.awt.Color(255, 0, 0));
        jLabel100.setText("Lê Tấn Thành");

        jLabel101.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel101.setForeground(new java.awt.Color(255, 0, 0));
        jLabel101.setText("Lý Kiến Huy");

        jLabel102.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel102.setForeground(new java.awt.Color(255, 0, 0));
        jLabel102.setText("Lê Minh Phúc");

        javax.swing.GroupLayout FrameThongtindoanLayout = new javax.swing.GroupLayout(FrameThongtindoan.getContentPane());
        FrameThongtindoan.getContentPane().setLayout(FrameThongtindoanLayout);
        FrameThongtindoanLayout.setHorizontalGroup(
            FrameThongtindoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameThongtindoanLayout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addComponent(jLabel91)
                .addGap(152, 152, 152))
            .addGroup(FrameThongtindoanLayout.createSequentialGroup()
                .addGroup(FrameThongtindoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrameThongtindoanLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel97))
                    .addGroup(FrameThongtindoanLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel96))
                    .addGroup(FrameThongtindoanLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel92)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(FrameThongtindoanLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(FrameThongtindoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel93)
                    .addGroup(FrameThongtindoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel99, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel95, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(FrameThongtindoanLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(FrameThongtindoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel100)
                            .addComponent(jLabel94)
                            .addComponent(jLabel101)
                            .addComponent(jLabel102))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FrameThongtindoanLayout.setVerticalGroup(
            FrameThongtindoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameThongtindoanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel91)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel92)
                .addGap(18, 18, 18)
                .addComponent(jLabel93)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel100)
                .addGap(5, 5, 5)
                .addComponent(jLabel94)
                .addGap(9, 9, 9)
                .addComponent(jLabel101)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel102)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel99)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel95)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel96)
                .addGap(18, 18, 18)
                .addComponent(jLabel97)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbpFrame.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbpFrame.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tbpFrame.setFont(new java.awt.Font("Segoe UI Light", 1, 20)); // NOI18N

        javax.swing.GroupLayout tabNhanVienLayout = new javax.swing.GroupLayout(tabNhanVien);
        tabNhanVien.setLayout(tabNhanVienLayout);
        tabNhanVienLayout.setHorizontalGroup(
            tabNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1092, Short.MAX_VALUE)
        );
        tabNhanVienLayout.setVerticalGroup(
            tabNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );

        tbpFrame.addTab("Nhân viên", tabNhanVien);

        javax.swing.GroupLayout tabHopDongLayout = new javax.swing.GroupLayout(tabHopDong);
        tabHopDong.setLayout(tabHopDongLayout);
        tabHopDongLayout.setHorizontalGroup(
            tabHopDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1092, Short.MAX_VALUE)
        );
        tabHopDongLayout.setVerticalGroup(
            tabHopDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );

        tbpFrame.addTab("Hợp đồng", tabHopDong);

        javax.swing.GroupLayout tabViPhamLayout = new javax.swing.GroupLayout(tabViPham);
        tabViPham.setLayout(tabViPhamLayout);
        tabViPhamLayout.setHorizontalGroup(
            tabViPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1092, Short.MAX_VALUE)
        );
        tabViPhamLayout.setVerticalGroup(
            tabViPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );

        tbpFrame.addTab("Vi phạm", tabViPham);

        javax.swing.GroupLayout tabDonNghiPhepLayout = new javax.swing.GroupLayout(tabDonNghiPhep);
        tabDonNghiPhep.setLayout(tabDonNghiPhepLayout);
        tabDonNghiPhepLayout.setHorizontalGroup(
            tabDonNghiPhepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1092, Short.MAX_VALUE)
        );
        tabDonNghiPhepLayout.setVerticalGroup(
            tabDonNghiPhepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );

        tbpFrame.addTab("Đơn nghỉ phép", tabDonNghiPhep);

        javax.swing.GroupLayout tabLuongLayout = new javax.swing.GroupLayout(tabLuong);
        tabLuong.setLayout(tabLuongLayout);
        tabLuongLayout.setHorizontalGroup(
            tabLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1092, Short.MAX_VALUE)
        );
        tabLuongLayout.setVerticalGroup(
            tabLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );

        tbpFrame.addTab("Lương", tabLuong);

        javax.swing.GroupLayout tabPhongBanLayout = new javax.swing.GroupLayout(tabPhongBan);
        tabPhongBan.setLayout(tabPhongBanLayout);
        tabPhongBanLayout.setHorizontalGroup(
            tabPhongBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1092, Short.MAX_VALUE)
        );
        tabPhongBanLayout.setVerticalGroup(
            tabPhongBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );

        tbpFrame.addTab("Phòng ban", tabPhongBan);

        javax.swing.GroupLayout tabDuAnLayout = new javax.swing.GroupLayout(tabDuAn);
        tabDuAn.setLayout(tabDuAnLayout);
        tabDuAnLayout.setHorizontalGroup(
            tabDuAnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1092, Short.MAX_VALUE)
        );
        tabDuAnLayout.setVerticalGroup(
            tabDuAnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );

        tbpFrame.addTab("Dự án", tabDuAn);

        javax.swing.GroupLayout tabThongKeLayout = new javax.swing.GroupLayout(tabThongKe);
        tabThongKe.setLayout(tabThongKeLayout);
        tabThongKeLayout.setHorizontalGroup(
            tabThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1092, Short.MAX_VALUE)
        );
        tabThongKeLayout.setVerticalGroup(
            tabThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );

        tbpFrame.addTab("Thống kê", tabThongKe);

        btnTTPM.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnTTPM.setText("Thông tin phần mềm");
        btnTTPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTTPMActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(tbpFrame)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTTPM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbpFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTTPM)
                    .addComponent(btnThoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void initChildComponents() {
        //Khoi tao cac giao dien con
        pnThongTinNhanVien = new NhanVienGUI();
        pnTTHD = new HopDongGUI();
        pnThongTinViPham = new ViPhamGUI();
        pnDonNghiPhep = new DonNghiPhepGUI();
        pnLuongNV = new LuongGUI();
        pnPhongBan = new PhongBanGUI();
        pnDuAn = new DuAnGUI();
        pnThongKe = new ThongKeGUI();
        
        tabNhanVien.setLayout(new GridLayout());
        tabHopDong.setLayout(new GridLayout());
        tabViPham.setLayout(new GridLayout());
        tabDonNghiPhep.setLayout(new GridLayout());
        tabLuong.setLayout(new GridLayout());
        tabPhongBan.setLayout(new GridLayout());
        tabDuAn.setLayout(new GridLayout());
        tabThongKe.setLayout(new GridLayout());
        
        //Them cac giao dien con vao menu TabbedPane
        tabNhanVien.add(pnThongTinNhanVien);
        tabHopDong.add(pnTTHD);
        tabViPham.add(pnThongTinViPham);
        tabDonNghiPhep.add(pnDonNghiPhep);
        tabLuong.add(pnLuongNV); 
        tabPhongBan.add(pnPhongBan);  
        tabDuAn.add(pnDuAn);  
        tabThongKe.add(pnThongKe);  
        
        
        // Lấy tọa độ x, y dựa trên độ phân giải của thiết bị
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        FrameThongtindoan.setTitle("Thông tin đồ án");
        FrameThongtindoan.setLocation(x, y);
        
        this.setTitle("Quản lý nhân viên");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }
    
    
    /**
    * Xu ly su kien
    **/
    // <editor-fold defaultstate="collapsed" desc="Event Handling">   
    private void btnTTPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTTPMActionPerformed
        FrameThongtindoan.pack();
        FrameThongtindoan.setVisible(true);
    }//GEN-LAST:event_btnTTPMActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        FrameThongtindoan.dispose();
        dispose();
    }//GEN-LAST:event_btnThoatActionPerformed
    //</editor-fold>
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(qlns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(qlns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(qlns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(qlns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new qlns().setVisible(true);
            }
        });
    }

    
    // <editor-fold defaultstate="collapsed" desc="Variables Declaration">   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog FrameThongtindoan;
    private javax.swing.JButton btnTTPM;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel tabDonNghiPhep;
    private javax.swing.JPanel tabDuAn;
    private javax.swing.JPanel tabHopDong;
    private javax.swing.JPanel tabLuong;
    private javax.swing.JPanel tabNhanVien;
    private javax.swing.JPanel tabPhongBan;
    private javax.swing.JPanel tabThongKe;
    private javax.swing.JPanel tabViPham;
    private javax.swing.JTabbedPane tbpFrame;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>
}
