package GUI;

import java.io.File;
import javax.swing.JFileChooser;

public class ThongKeGUI extends javax.swing.JPanel {

    public ThongKeGUI() {
        initComponents();
        rebuildFrame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnThongKe = new javax.swing.JPanel();
        lbThongKe = new javax.swing.JLabel();
        lbNgayKTThongKe = new javax.swing.JLabel();
        lbNgayBDThongKe = new javax.swing.JLabel();
        btnThongKe = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        lbFile = new javax.swing.JLabel();

        lbThongKe.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        lbThongKe.setText("Thống kê");

        lbNgayKTThongKe.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lbNgayKTThongKe.setText("Đến ngày");

        lbNgayBDThongKe.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lbNgayBDThongKe.setText("Từ ngày");

        btnThongKe.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnThongKe.setText("Import");
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        btnExport.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnExport.setText("Export");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        lbFile.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N

        javax.swing.GroupLayout pnThongKeLayout = new javax.swing.GroupLayout(pnThongKe);
        pnThongKe.setLayout(pnThongKeLayout);
        pnThongKeLayout.setHorizontalGroup(
            pnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongKeLayout.createSequentialGroup()
                .addGroup(pnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThongKeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbThongKe))
                    .addGroup(pnThongKeLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(lbNgayBDThongKe)
                        .addGap(195, 195, 195)
                        .addComponent(lbNgayKTThongKe)
                        .addGap(197, 197, 197)
                        .addGroup(pnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnThongKeLayout.createSequentialGroup()
                                .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(125, 125, 125)
                                .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbFile, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        pnThongKeLayout.setVerticalGroup(
            pnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongKeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbThongKe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNgayKTThongKe)
                    .addComponent(lbNgayBDThongKe)
                    .addComponent(btnExport)
                    .addComponent(btnThongKe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbFile, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 525, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1096, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void rebuildFrame() {
        
    }
    
    
    // <editor-fold defaultstate="collapsed" desc="Event Handling">   
    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        JFileChooser fc;
        File f;
        fc = new JFileChooser();
        fc.showOpenDialog(null);
        f = fc.getSelectedFile();
        lbFile.setText(f.getName());
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed

    }//GEN-LAST:event_btnExportActionPerformed
    //</editor-fold>

    
    // <editor-fold defaultstate="collapsed" desc="Variables Declaration">   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JLabel lbFile;
    private javax.swing.JLabel lbNgayBDThongKe;
    private javax.swing.JLabel lbNgayKTThongKe;
    private javax.swing.JLabel lbThongKe;
    private javax.swing.JPanel pnThongKe;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>
}
