package GUI;

import BUS.NhanVienBUS;
import BUS.ViPham_BUS;
import DTO.NhanVienDTO;
import DTO.ViPham_DTO;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ViPhamGUI extends javax.swing.JPanel {
    ViPham_BUS VPBUS=new ViPham_BUS();
    NhanVienBUS NVBUS=new NhanVienBUS();
    ArrayList<ViPham_DTO> arrVP=new ArrayList<ViPham_DTO>();
    DefaultTableModel modelVP;
    DefaultTableModel modelNV;
    public ViPhamGUI() {
        initComponents();
        rebuildFrame();
        modelVP=(DefaultTableModel) tbVP.getModel();
        modelNV=(DefaultTableModel) tbNVVP.getModel();
        loadListViPham();
        loadListNhanVien();
        KhoiTaoBTN();
    }
    public void loadListNhanVien(){
        modelNV.setRowCount(0);
        try {
            NVBUS.docDSNV();
        } catch (Exception ex) {
            Logger.getLogger(ViPhamGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        for(int i=0;i<NhanVienBUS.dsnv.size();i++){
            NhanVienDTO NV=NhanVienBUS.dsnv.get(i);
            String id_nhanvien=NV.getId();
            String tennhanvien=NV.getName();
            Object[] row={id_nhanvien,tennhanvien};
            modelNV.addRow(row);
        }
    }
    public void loadListViPham(){ 
        modelVP.setRowCount(0);
        arrVP=VPBUS.getAllViPham();
        for(int i=0;i<arrVP.size();i++){
            ViPham_DTO VP=arrVP.get(i);
            int id=VP.getID_vipham();
            String tennhanvien=VP.getTennhanvien();
            String lydovipham=VP.getLydo();
            String ngayvipham= VP.getNgay();
            int mucphat=VP.getTienphat();
            Object[] row={id,tennhanvien,lydovipham,ngayvipham,mucphat};
            modelVP.addRow(row);
        }
    }
    public void KhoiTaoBTN(){
        btnXoaVP.setEnabled(false);
        btnSuaVP.setEnabled(false);
    }
    public void resetText(){
        tfIDNVVP.setText("");
        tfTenNVVP.setText("");
        Date date=null;
        taLiDoVP.setText("");
        tfNgayVP.setDate(date);
        tfMucPhat.setText("");
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTTVP = new javax.swing.JPanel();
        pnTimKiemVP = new javax.swing.JPanel();
        lbTimKiemVP = new javax.swing.JLabel();
        tfTimKiemVP = new javax.swing.JTextField();
        spTimKiemVP = new javax.swing.JScrollPane();
        tbVP = new javax.swing.JTable();
        cbTimKiemVP = new javax.swing.JComboBox<>();
        lbTTVP = new javax.swing.JLabel();
        lbTenNVVP = new javax.swing.JLabel();
        tfTenNVVP = new javax.swing.JTextField();
        lbLiDoVP = new javax.swing.JLabel();
        lbMucPhat = new javax.swing.JLabel();
        lbNgayVP = new javax.swing.JLabel();
        spLiDoViPham = new javax.swing.JScrollPane();
        taLiDoVP = new javax.swing.JTextArea();
        tfMucPhat = new javax.swing.JTextField();
        btnThemVP = new javax.swing.JButton();
        btnSuaVP = new javax.swing.JButton();
        btnXoaVP = new javax.swing.JButton();
        tfNgayVP = new com.toedter.calendar.JDateChooser();
        lbID = new javax.swing.JLabel();
        tfIDNVVP = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbNVVP = new javax.swing.JTable();

        pnTTVP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnTTVPMousePressed(evt);
            }
        });

        pnTimKiemVP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbTimKiemVP.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lbTimKiemVP.setText("Tìm kiếm");

        tfTimKiemVP.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        tfTimKiemVP.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfTimKiemVPCaretUpdate(evt);
            }
        });

        tbVP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Tên nhân viên", "Lí do vi phạm", "Ngày vi phạm", "Mức phạt"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbVP.setRowHeight(25);
        tbVP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbVPMousePressed(evt);
            }
        });
        spTimKiemVP.setViewportView(tbVP);
        if (tbVP.getColumnModel().getColumnCount() > 0) {
            tbVP.getColumnModel().getColumn(0).setMinWidth(80);
            tbVP.getColumnModel().getColumn(0).setMaxWidth(80);
            tbVP.getColumnModel().getColumn(1).setMinWidth(200);
            tbVP.getColumnModel().getColumn(1).setMaxWidth(200);
            tbVP.getColumnModel().getColumn(3).setMinWidth(160);
            tbVP.getColumnModel().getColumn(3).setMaxWidth(160);
            tbVP.getColumnModel().getColumn(4).setMinWidth(120);
            tbVP.getColumnModel().getColumn(4).setMaxWidth(120);
        }

        cbTimKiemVP.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        cbTimKiemVP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "ID", "Tên nhân viên", "Ngày vi phạm", "Mức phạt" }));

        javax.swing.GroupLayout pnTimKiemVPLayout = new javax.swing.GroupLayout(pnTimKiemVP);
        pnTimKiemVP.setLayout(pnTimKiemVPLayout);
        pnTimKiemVPLayout.setHorizontalGroup(
            pnTimKiemVPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiemVPLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbTimKiemVP)
                .addGap(18, 18, 18)
                .addComponent(tfTimKiemVP, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbTimKiemVP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnTimKiemVPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spTimKiemVP)
                .addContainerGap())
        );
        pnTimKiemVPLayout.setVerticalGroup(
            pnTimKiemVPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiemVPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTimKiemVPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTimKiemVPLayout.createSequentialGroup()
                        .addGap(0, 5, Short.MAX_VALUE)
                        .addGroup(pnTimKiemVPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTimKiemVP)
                            .addComponent(tfTimKiemVP, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cbTimKiemVP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spTimKiemVP, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lbTTVP.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        lbTTVP.setText("Thông tin vi phạm");

        lbTenNVVP.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lbTenNVVP.setText("Tên nhân viên");

        tfTenNVVP.setFont(new java.awt.Font("Segoe UI Light", 1, 13)); // NOI18N

        lbLiDoVP.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lbLiDoVP.setText("Lí do vi phạm");

        lbMucPhat.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lbMucPhat.setText("Mức phạt");

        lbNgayVP.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lbNgayVP.setText("Ngày vi phạm");

        taLiDoVP.setColumns(20);
        taLiDoVP.setFont(new java.awt.Font("Segoe UI Light", 1, 13)); // NOI18N
        taLiDoVP.setLineWrap(true);
        taLiDoVP.setRows(5);
        spLiDoViPham.setViewportView(taLiDoVP);

        tfMucPhat.setFont(new java.awt.Font("Segoe UI Light", 1, 13)); // NOI18N

        btnThemVP.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnThemVP.setText("Thêm");
        btnThemVP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemVPActionPerformed(evt);
            }
        });

        btnSuaVP.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnSuaVP.setText("Sửa");
        btnSuaVP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaVPActionPerformed(evt);
            }
        });

        btnXoaVP.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnXoaVP.setText("Xóa");
        btnXoaVP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaVPActionPerformed(evt);
            }
        });

        tfNgayVP.setDateFormatString("yyyy-MM-dd");
        tfNgayVP.setMaxSelectableDate(new java.util.Date(253370743267000L));

        lbID.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lbID.setText("ID nhân viên");

        tbNVVP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID_Nhân viên", "Tên nhân viên"
            }
        ));
        tbNVVP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbNVVPMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbNVVP);

        javax.swing.GroupLayout pnTTVPLayout = new javax.swing.GroupLayout(pnTTVP);
        pnTTVP.setLayout(pnTTVPLayout);
        pnTTVPLayout.setHorizontalGroup(
            pnTTVPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTTVPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTTVPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTTVPLayout.createSequentialGroup()
                        .addComponent(pnTimKiemVP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pnTTVPLayout.createSequentialGroup()
                        .addGroup(pnTTVPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnTTVPLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(pnTTVPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbTenNVVP)
                                    .addComponent(lbID)
                                    .addGroup(pnTTVPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbNgayVP)
                                        .addGroup(pnTTVPLayout.createSequentialGroup()
                                            .addComponent(lbMucPhat)
                                            .addGap(26, 26, 26)))
                                    .addComponent(lbLiDoVP))
                                .addGap(49, 49, 49)
                                .addGroup(pnTTVPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnTTVPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tfIDNVVP, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfTenNVVP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                                    .addComponent(spLiDoViPham, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnTTVPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tfNgayVP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tfMucPhat, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lbTTVP))
                        .addGroup(pnTTVPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTTVPLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65))
                            .addGroup(pnTTVPLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(btnThemVP, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(btnSuaVP, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(btnXoaVP, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        pnTTVPLayout.setVerticalGroup(
            pnTTVPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTTVPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTTVP)
                .addGroup(pnTTVPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTTVPLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnTTVPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThemVP)
                            .addComponent(btnSuaVP)
                            .addComponent(btnXoaVP))
                        .addGap(12, 12, 12))
                    .addGroup(pnTTVPLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnTTVPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbID)
                            .addComponent(tfIDNVVP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnTTVPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTenNVVP)
                            .addComponent(tfTenNVVP, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnTTVPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbNgayVP)
                            .addComponent(tfNgayVP, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnTTVPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spLiDoViPham, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbLiDoVP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 24, Short.MAX_VALUE)
                        .addGroup(pnTTVPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMucPhat)
                            .addComponent(tfMucPhat, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)))
                .addComponent(pnTimKiemVP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnTTVP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTTVP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void rebuildFrame() {
        
    }
    
    
    // <editor-fold defaultstate="collapsed" desc="Event Handling">   
    private void btnThemVPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemVPActionPerformed
        try{
        //Kiểm tra tất cả textfield của JFrame có dữ liệu không
        if(tfIDNVVP.getText().trim().equals("")||
           tfTenNVVP.getText().trim().equals("")||
           taLiDoVP.getText().trim().equals("")||
           tfMucPhat.getText().trim().equals("")){
           JOptionPane.showMessageDialog(this,"Vui lòng nhập đủ thông tin");
        }else{//Nếu không rỗng thì set dữ liệu vào vp rồi gọi hàm add từ lớp BUS
           SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
           String getdate = format.format(tfNgayVP.getDate());
           ViPham_DTO vp=new ViPham_DTO();
           vp.setID_nhanvien(tfIDNVVP.getText());
           vp.setTennhanvien(tfTenNVVP.getText());
           vp.setLydo(taLiDoVP.getText());
           vp.setNgay(getdate);
           vp.setTienphat(Integer.parseInt(tfMucPhat.getText()));
           JOptionPane.showMessageDialog(this, VPBUS.addViPham(vp));
           loadListViPham();
        }
    }catch(Exception ex){
        JOptionPane.showMessageDialog(this, "Thêm thất bại");
        }
    }//GEN-LAST:event_btnThemVPActionPerformed

    private void btnSuaVPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaVPActionPerformed
      try{
        //Kiểm tra tất cả textfield của JFrame có dữ liệu không
        if(tfIDNVVP.getText().trim().equals("")||
           tfTenNVVP.getText().trim().equals("")||
           taLiDoVP.getText().trim().equals("")||
           tfMucPhat.getText().trim().equals("")){
           JOptionPane.showMessageDialog(this,"Vui lòng nhập đủ thông tin");
        }else{//Nếu không rỗng thì set dữ liệu vào vp rồi gọi hàm update từ lớp BUS
           int id=(int) tbVP.getValueAt(tbVP.getSelectedRow(),0);
           SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
           String getdate = format.format(tfNgayVP.getDate());
           ViPham_DTO vp=new ViPham_DTO();
           vp.setID_vipham(id);
           vp.setID_nhanvien(tfIDNVVP.getText());
           vp.setTennhanvien(tfTenNVVP.getText());
           vp.setLydo(taLiDoVP.getText());
           vp.setNgay(getdate);
           vp.setTienphat(Integer.parseInt(tfMucPhat.getText()));
           JOptionPane.showMessageDialog(this, VPBUS.updateViPham(vp));
           //Load lại dữ liệu sau khi thêm vi phạm
           loadListViPham();
        }
    }catch(Exception ex){
        JOptionPane.showMessageDialog(this, "Sửa thất bại");
          System.out.println(ex);
        }
      //Khi thực hiện xong thì nút xóa và nút sửa ẩn đi vì không có tương tác với table 
      btnSuaVP.setEnabled(false);
      btnXoaVP.setEnabled(false);
    }//GEN-LAST:event_btnSuaVPActionPerformed

    private void btnXoaVPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaVPActionPerformed
       int i=tbVP.getSelectedRow();
       //Lấy dòng thứ i mà được chon trong table 
       try{
       if(i>=0){
        //Lấy cột đầu tiên là id để gọi hàm del bên BUS
        JOptionPane.showMessageDialog(this, VPBUS.delViPham((int) tbVP.getValueAt(i,0)));
        Date date=null;
        //Xóa hết dữ liệu của tất cả textfield khi thực hiện nút hiển thị
        tfIDNVVP.setText("");
        tfTenNVVP.setText("");
        taLiDoVP.setText("");
        tfNgayVP.setDate(date);
        tfMucPhat.setText("");
       }
       else{
           JOptionPane.showMessageDialog(this,"Vui lòng chọn vi phạm để xóa");
       }
       //Load lại bảng dữ liệu sau khi xóa 
       loadListViPham();
       }catch(Exception ex){
           JOptionPane.showMessageDialog(this, "Xóa thất bại");
       }
       //Khi thực hiện xong thì nút xóa và nút sửa ẩn đi vì không có tương tác với table 
       btnXoaVP.setEnabled(false);
       btnSuaVP.setEnabled(false);
    }//GEN-LAST:event_btnXoaVPActionPerformed

    private void tfTimKiemVPCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfTimKiemVPCaretUpdate
        modelVP.setRowCount(0);
        //Xóa tất cả dữ liệu của bảng vi phạm
        try{
        if(!tfTimKiemVP.getText().trim().equals("")){
        String st=tfTimKiemVP.getText();
        //Lấy dữ liệu từ textfield tìm kiếm 
        int select=0;//Khai báo thêm 1 dữ liệu int để truyền vào hàm tìm kiếm 
        if(cbTimKiemVP.getSelectedItem().equals("ID")){
            //Với id có kiểu dữ liệu int nên đưa kiểu String từ textfield sang int
                select=Integer.parseInt(tfTimKiemVP.getText());
                arrVP=VPBUS.TimKiemViPham(st,select,0);
            }
        if(cbTimKiemVP.getSelectedItem().equals("Mức phạt")){
            //Với tiền phạt có kiểu dữ liệu int nên đưa kiểu String từ textfield sang int
                select=Integer.parseInt(tfTimKiemVP.getText());
                arrVP=VPBUS.TimKiemViPham(st,select,1);
            }
        
        if(cbTimKiemVP.getSelectedItem().equals("Tên nhân viên")){
                arrVP=VPBUS.TimKiemViPham(st,select,2);
        }
        if(cbTimKiemVP.getSelectedItem().equals("Ngày vi phạm")){
                arrVP=VPBUS.TimKiemViPham(st,select,3);
        }
        if(cbTimKiemVP.getSelectedItem().equals("Tất cả")){
            //Với lựa chon tất cả thì vừa có kiểu int và kiểu String
            //
                try{
                    select=Integer.parseInt(tfTimKiemVP.getText());
                }catch(NumberFormatException e){
                    select=0;
                }
                arrVP=VPBUS.TimKiemViPham(st,select,4);           
        }
                for(int i=0;i<arrVP.size();i++){
                ViPham_DTO VP=arrVP.get(i);
                int id=VP.getID_vipham();
                String tennhanvien=VP.getTennhanvien();
                String lydo=VP.getLydo();
                String ngayvipham= VP.getNgay();
                int mucphat=VP.getTienphat();
                Object[] row={id,tennhanvien,lydo,ngayvipham,mucphat};
                modelVP.addRow(row);
            }
        }
        else{
            loadListViPham();
        }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_tfTimKiemVPCaretUpdate

    private void tbVPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbVPMousePressed
        btnXoaVP.setEnabled(true);
        btnSuaVP.setEnabled(true);
        int id=(int) tbVP.getValueAt(tbVP.getSelectedRow(), 0);
        ViPham_DTO VP= VPBUS.HienThiVP(id);
        Date date = null;
        try {
            date = new SimpleDateFormat("yyyy-MM-dd").parse(VP.getNgay());
        } catch (ParseException ex) {
            Logger.getLogger(ViPhamGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        tfIDNVVP.setText(VP.getID_vipham()+"");
        tfTenNVVP.setText(VP.getTennhanvien());
        taLiDoVP.setText(VP.getLydo());
        tfNgayVP.setDate(date);
        tfMucPhat.setText(VP.getTienphat()+"");
    }//GEN-LAST:event_tbVPMousePressed

    private void pnTTVPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnTTVPMousePressed
        KhoiTaoBTN();
        tbVP.getSelectionModel().clearSelection();
        tbNVVP.getSelectionModel().clearSelection();
        loadListNhanVien();
        resetText();
    }//GEN-LAST:event_pnTTVPMousePressed

    private void tbNVVPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNVVPMousePressed
        tfTenNVVP.setText(tbNVVP.getValueAt(tbNVVP.getSelectedRow(),1)+"");
        tfIDNVVP.setText(tbNVVP.getValueAt(tbNVVP.getSelectedRow(),0)+"");
    }//GEN-LAST:event_tbNVVPMousePressed
    //</editor-fold>
    // <editor-fold defaultstate="collapsed" desc="Variables Declaration">   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuaVP;
    private javax.swing.JButton btnThemVP;
    private javax.swing.JButton btnXoaVP;
    private javax.swing.JComboBox<String> cbTimKiemVP;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbLiDoVP;
    private javax.swing.JLabel lbMucPhat;
    private javax.swing.JLabel lbNgayVP;
    private javax.swing.JLabel lbTTVP;
    private javax.swing.JLabel lbTenNVVP;
    private javax.swing.JLabel lbTimKiemVP;
    private javax.swing.JPanel pnTTVP;
    private javax.swing.JPanel pnTimKiemVP;
    private javax.swing.JScrollPane spLiDoViPham;
    private javax.swing.JScrollPane spTimKiemVP;
    private javax.swing.JTextArea taLiDoVP;
    private javax.swing.JTable tbNVVP;
    private javax.swing.JTable tbVP;
    private javax.swing.JTextField tfIDNVVP;
    private javax.swing.JTextField tfMucPhat;
    private com.toedter.calendar.JDateChooser tfNgayVP;
    private javax.swing.JTextField tfTenNVVP;
    private javax.swing.JTextField tfTimKiemVP;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>
}
